module.exports = {
  enabled: true,
  maxMessages: 5,
  timeWindow: 3,
  cooldownTime: 10,
  sendWarning: true,
  deleteWarningDelay: 15,
  exemptChannels: [],
  exemptRoles: [],
  exemptUsers: [
    ""
  ],
  "embed": {
    color: "#F04747",
    title: "Spam detected!",
    description: "**{username}**, please do not send so many messages in a short period of time.",
    "footer": process.env.FOOTER_TEXT ||"",
    "footerIconUrl": process.env.EMBED_FOOTER_IMAGE_URL || "",
    showTimestamp: true
  },
  "punishment": {
    enabled: true,
    "type": "mute",
    muteDuration: 5,
    reason: "Send spam messages"
  },
  "logging": {
    enabled: false,
    "channelId": ""
  },
  "badWords": {
    enabled: true,
    "additionalWords": [
      "arsch",
      "arschloch",
      "arschkriecher",
      "arschgeige",
      "arschgesicht",
      "affenarsch",
      "blödmann",
      "blödkuh",
      "blödhammel",
      "blödfisch",
      "depp",
      "dummkopf",
      "dummsack",
      "dummbatzen",
      "dummbatz",
      "fick dich",
      "ficken",
      "ficker",
      "fresse",
      "fotze",
      "gehirnamputiert",
      "hackfresse",
      "hirni",
      "hirnloser",
      "honk",
      "hurensohn",
      "hure",
      "idiot",
      "kackbratze",
      "kacke",
      "kackhaufen",
      "kackvogel",
      "klappspaten",
      "kotzbrocken",
      "lümmel",
      "miststück",
      "missgeburt",
      "mongo",
      "neandertaler",
      "penner",
      "pimmel",
      "pissnelke",
      "pisskopf",
      "scheiße",
      "scheißkerl",
      "scheißhaufen",
      "scheißdreck",
      "scheißer",
      "schlampe",
      "schwachkopf",
      "schwachmat",
      "schwanzlutscher",
      "schwein",
      "spacko",
      "spasti",
      "spastiker",
      "trottel",
      "verpisst euch",
      "verpiss dich",
      "vollidiot",
      "wichser",
      "wichskopf",
      "wichsgriffel",
      "zicke",
      "zippe"
    ],
    "deleteMessage": true,
    "punishUser": true,
    "embed": {
      color: "#F04747",
      title: "Swear word recognized!",
      description: "**{username}**, please do not use inappropriate language.",
      "footer": process.env.FOOTER_TEXT || "",
      "footerIconUrl": process.env.EMBED_FOOTER_IMAGE_URL ||"",
      "showTimestamp": true
    }
  },
  "suspiciousLinks": {
    enabled: true,
    "suspiciousDomains": [
      "bit.ly",
      "goo.gl",
      "tinyurl.com",
      "is.gd",
      "ow.ly",
      "t.co",
      "grabify.link",
      "iplogger.org",
      "2no.co",
      "ipgrabber.ru",
      "iplis.ru",
      "02ip.ru",
      "iplogger.com",
      "iplogger.ru",
      "yip.su",
      "iplogger.co",
      "iplogger.info",
      "ipgrabber.com",
      "ipgraber.ru",
      "lovebird.guru",
      "trulove.guru",
      "dateing.club",
      "shrekis.life",
      "headshot.monster",
      "gaming-at-my.best",
      "progaming.monster",
      "yourmy.monster",
      "imageshare.best",
      "screenshot.best",
      "gamingfun.me",
      "catsnthing.com",
      "catsnthings.fun",
      "curiouscat.club",
      "joinmy.site",
      "fortnitechat.site",
      "fortnight.space",
      "freegiftcards.co",
      "stopify.co",
      "leancoding.co"
    ],
    deleteMessage: true,
    punishUser: true,
    "embed": {
      color: "#F04747",
      title: "Suspicious link detected!",
      description: "**{username}**, please do not send suspicious links.",
      "footer": process.env.FOOTER_TEXT ||"",
      "footerIconUrl": process.env.EMBED_FOOTER_IMAGE_URL || "",
      "showTimestamp": true
    }
  }
}